services:
  otel-collector:
    image: ghcr.io/edgar454/otel-collector:latest
    container_name: otel_collector
    ports:
      - "4317:4317"   
      - "4318:4318"   
    networks:
      - cups_network

  tempo:
    image: ghcr.io/edgar454/otel-collector:latest
    container_name: tempo
    volumes:
      - tempo_data:/var/tempo
    networks:
      - cups_network

  prometheus:
    image: ghcr.io/edgar454/prometheus:latest 
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    networks:
      - cups_network

  postgres-exporter:
    image: ghcr.io/edgar454/postgres-exporter:latest
    container_name: cups_postgres-exporter
    environment:
      PG_EXPORTER_DSN: postgresql://${EXPORTER_USER}:${POSTGRES_EXPORTER_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      PG_EXPORTER_PORT: 9187
    restart: unless-stopped
    depends_on:
      postgres:
        condition: "service_healthy"
    networks:
      - cups_network

  grafana:
    image: ghcr.io/edgar454/grafana:latest
    container_name: grafana
    environment:
      POSTGRES_USER: ${POSTGRES_GRAFANA_USER:-grafana_user}
      POSTGRES_PASSWORD: ${POSTGRES_GRAFANA_PASSWORD:-grafana_user_password}
      POSTGRES_DB: ${POSTGRES_GRAFANA_DB:-postgres}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - cups_network

volumes:
  tempo_data:
  grafana_data:
  prometheus_data:
