
services:
  postgres :
    image: postgres:18-alpine
    container_name: cups_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      API_PASSWORD: ${API_PASSWORD:-api_password}
      POSTGRES_EXPORTER_PASSWORD: ${POSTGRES_EXPORTER_PASSWORD:-exporter_password}
      WORKER_PASSWORD: ${PIPELINE_PASSWORD:-pipeline_password}
      GRAFANA_USER_PASSWORD: ${GRAFANA_USER_PASSWORD:-grafana_user_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cups_network
  
  init-permissions:
    image: ubuntu:22.04
    volumes:
      - ./permissions/init_permissions.sh:/init_permissions.sh
      - shared_files:/data
    command: ["sh", "/init_permissions.sh"]

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: cups_filebrowser
    restart: always
    user: "1000:410"
    ports:
      - "8080:80"
    volumes:
      - shared_files:/srv
      - filebrowser_data:/database
    depends_on:
      init-permissions:
        condition: service_completed_successfully
    networks:
      - cups_network

  api:
    build:
      context: . 
      dockerfile:  api/Dockerfile
    container_name: cups_api
    ports:
        - 8081:8080
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_USER: ${API_USER:-api_user}
      DB_PASSWORD: ${API_PASSWORD:-api_password}
      DB_SSLMODE: disable
      CUPS_SERVER_URL: cups_server:631
      CUPS_USER: ${CUPS_USER:-admin}
      CUPS_PASSWORD: ${CUPS_PASSWORD:-admin}
      FILE_FOLDER: /files
      OTEL_SERVICE_NAME: cups-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      ENV: development
    volumes:
      - shared_files:/files
    depends_on:
      postgres:
        condition: 'service_healthy'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cups_network
  
  frontend:
    build:
      context: . 
      dockerfile:  printer-platform-ui/Dockerfile
    container_name: cups_frontend
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: 'service_healthy'
    networks:
      - cups_network

  pipeline:
    build:
      context: . 
      dockerfile:  processing_pipeline/Dockerfile
    container_name: cups_pdf_pipeline
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_USER: ${PIPELINE_USER:-pipeline_worker}
      DB_PASSWORD: ${PIPELINE_PASSWORD:-pipeline_password}
      DB_SSLMODE: disable
      CUPS_SERVER_URL: cups_server:631
      CUPS_USER: ${CUPS_USER:-admin}
      CUPS_PASSWORD: ${CUPS_PASSWORD:-admin}
      FILE_FOLDER: '/files'
      OTEL_SERVICE_NAME: cups-pipeline
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    volumes:
      - shared_files:/files
    depends_on:
      postgres:
        condition: 'service_healthy'
      api:
        condition: 'service_healthy'
      cups_server:
        condition: 'service_healthy'
      init-permissions:
        condition: service_completed_successfully
    networks:
      - cups_network
  
  cups_server:
    build:  
      context: .
      dockerfile: cups_server/Dockerfile
    container_name: cups_server
    restart: always
    volumes:
      - ./cups_server/print_output:/var/spool/cups-pdf/
    post_start:
      - command: /bin/sh -c "/setup.sh > /tmp/hook.log 2>&1"
    ports:
      - "631:631"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:631 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cups_network
  
  dummy_printer:
    build:
      context: .
      dockerfile: dummy_printer/Dockerfile
    container_name: dummy_printer
    volumes:
      - ./dummy_printer/jobs:/jobs
    restart: always
    ports:
      - "8631:8631"
    networks:
      - cups_network
    

volumes:
  postgres_data:
  filebrowser_data:
  shared_files:

networks:
  cups_network:
    driver: bridge
    name: cups_network
    ipam:
      config:
        - subnet: 172.28.0.0/24
