FROM ghcr.io/edgar454/pg_exporter:custom 
CMD ["--collector.locks",\
     "--collector.database",\
     "--collector.stat",\
     "--collector.replication",\
     "--collector.index",\
     "--collector.statements",\
     "--collector.tls",\
     "--collector.exporter"]